const trustedEmailProviders = [
  "gmail.com",
  "yahoo.com",
  "outlook.com",
  "aol.com",
  "icloud.com",
  "protonmail.com",
  "zoho.com",
  "yandex.com",
  "gmx.com",
  "hotmail.com",
  "live.com",
  "fastmail.com",
  "tutanota.com",
  "posteo.de",
  "mailbox.org",
  "lavabit.com",
  "startmail.com",
  "countermail.com",
  "hushmail.com",
  "scryptmail.com",
  "mailfence.com",
  "ctemplar.com",
  "bluegrasspals.com", // custom domain
  "pwry.net",
  "gmx.de",
  "garwood.day",
];
export default trustedEmailProviders;
